### ISSUE TITLE
Apache-2.0 License

### ISSUE THREAD

**Issue by rffontenelle** [pygreece/python-docs-gr#15]
/type bug

### Ποιος είναι ο τύπος του προβλήματος ή του σφάλματος που εντοπίσατε;

No preset types apply.

## Περίληψη προβλήματος

LICENSE file is set as Apache-2.0, but [PEP 545](https://peps.python.org/pep-0545/#setup-the-documentation-contribution-agreement) states that official translations of Python Docs must be under CC0. If the intention is to become official translation at some point, license should be changed.

**Οδηγίες για την αναπαραγωγή του σφάλματος**

## Επιθυμητή συμπεριφορά

No license conflict.

## Κάποια πρόταση για την επίλυση του προβλήματος

Add Contributing Agreement text to README.md and change license file to Creative Commons Zero (CC0).

**Comment by lysnikolaou** [comment]
Thanks for opening the issue @rffontenelle! Will change the licence.

**Comment by skpanagiotis** [comment]
You can assign this to me.

**Comment by thepetk** [comment]
Closing as it was done after https://github.com/pygreece/python-docs-gr/pull/138
