### ISSUE TITLE
[3.12] Translate `faq/installed.po`

### ISSUE THREAD

**Issue by thepetk** [pygreece/python-docs-gr#34]
/type translation

## Περιγραφή της εργασίας μετάφρασης

Το αρχείο αυτό θα πρέπει να μεταφραστεί στο 100%.

Η μετεφρασμένη έκδοση του αρχείου θα είναι διαθέσιμη στο https://docs.python.org/el/3.12/faq/installed.html.
Μέχρι τότε, θα φαίνεται η Αγγλική έκδοσης της σελίδας.

Παρακαλούμε, σχολιάστε μέσα στο issue εάν θέλετε αυτό το αρχείο να ανατεθεί σε σας. Ένα μέλος της διαχειριστικής ομάδας θα σας το αναθέσει το συντομότερο δυνατό, ώστε να μπορέσεται να το δουλέψετε.

Θυμηθείτε να ακουληθείσεται τις οδηγίες στον [οδηγό συνεισφοράς](https://github.com/pygreece/python-docs-gr/blob/main/CONTRIBUTING.md)

**Comment by dimpapas** [comment]
Θέλω να αναλάβω την μετάφραση του.

**Comment by thepetk** [comment]
@dimpapas σου το έκανα assign. Μια ερώτηση από μεριάς μου είναι αν είσαι μέλος στον pygreece discord server

**Comment by dimpapas** [comment]
> @dimpapas σου το έκανα assign. Μια ερώτηση από μεριάς μου είναι αν είσαι μέλος στον pygreece discord server

Ναι, είμαι και στον discord server το username μου είναι dimitris._05

**Comment by thepetk** [comment]
> > @dimpapas σου το έκανα assign. Μια ερώτηση από μεριάς μου είναι αν είσαι μέλος στον pygreece discord server
> 
> Ναι, είμαι και στον discord server το username μου είναι dimitris._05

Τέλεια σε έκανα ping!
