### ISSUE TITLE
[3.12] Translate `reference/introduction.po`

### ISSUE THREAD

**Issue by thepetk** [pygreece/python-docs-gr#512]
/type translation

## Περιγραφή της εργασίας μετάφρασης

Το αρχείο αυτό θα πρέπει να μεταφραστεί στο 100%.

Η μετεφρασμένη έκδοση του αρχείου θα είναι διαθέσιμη στο https://docs.python.org/el/3.12/reference/introduction.html.
Μέχρι τότε, θα φαίνεται η Αγγλική έκδοσης της σελίδας.

Παρακαλούμε, σχολιάστε μέσα στο issue εάν θέλετε αυτό το αρχείο να ανατεθεί σε σας. Ένα μέλος της διαχειριστικής ομάδας θα σας το αναθέσει το συντομότερο δυνατό, ώστε να μπορέσεται να το δουλέψετε.

Θυμηθείτε να ακουληθείσεται τις οδηγίες στον [οδηγό συνεισφοράς](https://github.com/pygreece/python-docs-gr/blob/main/CONTRIBUTING.md)

**Comment by steliosrotas** [comment]
Θα ήθελα να μεταφράσω αυτό το issue.

**Comment by thepetk** [comment]
@steliosrotas thanks για την συνεισφορά! Σου έκανα assign το issue :)

**Comment by steliosrotas** [comment]
Έχω τελειώσει την μετάφραση, αλλά δεν μου δουλεύει το powrap. Έχω την εντύπωση ότι το έχω κατεβασμένο, ωστόσο δεν μου το αναγνωρίζει. Όταν την πρώτη φορά έκανα precommit, μου έγραφε ότι το powrap ήταν failed. Τώρα που το ξανά έκανα όμως, μου το γράφει ως passed, ωστόσο μου γράφει failed για το pospell...![Image](https://github.com/user-attachments/assets/1a61f9b0-2941-44df-a1c7-0047a60b89de)
![Image](https://github.com/user-attachments/assets/5d8fdd8d-cf36-4785-ac95-681beba2b0c5)

**Comment by skpanagiotis** [comment]
Αρχικά σε ευχαρίστουμε για τον χρόνο σου και τη συνδρομή σου 🎯.

Από ότι καταλαβαίνω δουλεύεις με Windows χρησιμοποιώντας το WSL, και κρίνεται αναγκαίο να κάνουμε ενημέρωση τον οδηγό καθώς η διαδικασία που περιγράφουμε δεν είναι προσαρμόσιμη σε Windows περιβάλλον.

Συνεπώς η προσφορά σου και το πρόβλημα σου μας δίνει πάτημα για να βελτιώσουμε τον οδηγό.

Αναλυτικά στα θέματα που αντιμετωπίζεις.

# Command Not Found

Για το γεγονός ότι αντιμετωπίζεις το σφάλμα `powrap: command not found` σημαίνει ότι η εφαρμογή powrap δεν είναι στο environmental path. Στην δικιά σου περίπτωση από ότι καταλαβαίνω η εγκατάσταση έχει γίνει επιτυχώς. Συνεπώς θα πρέπει να το βάλεις στο path manually πληκτρολογώντας:

```bash
echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc
```

Έπειτα μπορεί να δεις αν έχει γίνει εγκατάσταση  του powrap και λειτουργεί στο μηχάνημα σου με τον παρακάτω κώδικα:

```bash
powrap --help
```

# Σφάλμα με λεξικό

Το σφάλμα που αντιμετωπίζει τώρα με το popspell είναι καθαρά επειδή δεν υπάρχει κάποιο λεξικό στο φάκελο `/usr/share/dict`.

Συνεπώς θα χρειαστεί να το προσθέσεις. 

Μπορείς να κατεβάσεις ένα ελληνικό [λεξικό](https://github.com/ONLYOFFICE/dictionaries/blob/master/el_GR/el_GR.dic) και να το καταχωρήσεις στο προαναφερόμενο φάκελο.
