### ISSUE TITLE
Empty cpython directory after cloning.

### ISSUE THREAD

**Issue by mgiannopoulos24** [pygreece/python-docs-gr#569]
/type bug

## Ποιος είναι ο τύπος του προβλήματος ή του σφάλματος που εντοπίσατε;

 /type cicd

## Περίληψη προβλήματος

Όταν κάνουμε clone και ακολουθήσουμε τις οδηγίες ως ένα σημείο είναι μια χαρά, όμως όταν φτάνουμε στο βήμα `pip install -r requirements.txt` ψάχνει ένα subdirectory του `cpython`. Το `cpython` είναι ένα submodule αλλά κατά το cloning δεν κατεβαίνει και αυτό.
 
**Οδηγίες για την αναπαραγωγή του σφάλματος**

Αφού έχουμε ακολουθήσει τις οδηγίες του `CONTRIBUTING.md` έως και το **βήμα 5**, μετά χρειάζεται να κάνουμε `pip install -r requirements.txt`. 

Αυτό θα βγάλει ένα μήνυμα λάθους όπως φαίνεται παρακάτω:

```console
(env) qwerty@qwerty-ubuntu:~/Downloads/python-docs-gr$ pip install -r requirements.txt 
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'cpython/Doc/constraints.txt'
```

## Επιθυμητή συμπεριφορά

Θα πρέπει να βρίσκει το `constraints.txt` στο `cpython`.

## Κάποια πρόταση για την επίλυση του προβλήματος

Να προστεθεί ένα επιπλέον βήμα στο `CONTRIBUTING.md` το οποίο θα μας λέει να χρησιμοποιήσουμε και το παρακάτω command ώστε να κάνουμε clone και το `cpython` ολόκληρο.

```console
git submodule update --init
```

**Comment by mgiannopoulos24** [comment]
Θα ήθελα να αναλάβω το συγκεκριμένο issue.

**Comment by lysnikolaou** [comment]
Assigned.
